AllCops:
  Exclude:
    - 'db/schema.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'

Lint/AssignmentInCondition:
  Exclude:
    - 'bin/spring'

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
