AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'

Lint/AssignmentInCondition:
  Exclude:
    - 'bin/spring'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'config/initializers/devise.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'config/routes.rb'

Metrics/AbcSize:
  Max: 18
  Exclude:
    - 'app/models/ability.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Lint/UnusedMethodArgument:
  Exclude:
    - 'app/helpers/application_helper.rb'

Metrics/MethodLength:
  Max: 15
